// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eybkafeibimerwpnqneo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5YmthZmVpYmltZXJ3cG5xbmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTg2NDgsImV4cCI6MjA2NTQ3NDY0OH0.VEIPOzIlfE5Y18Y-ovbx_MBPtPStLs0bCXsHtamO0Rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);